apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skywatch-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ladybaror/skywatch.git'
    targetRevision: HEAD
    path: helm/skywatch
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true