
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skywatch-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/skywatch.git' # הלינק ל-GitHub שלך
    targetRevision: HEAD
    path: helm/skywatch
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true