# helm/skywatch/values.yaml

replicaCount: 1

image:
  repository: skywatch-frontend
  tag: "749d6aff50877d0ad40af5413d6809522994060f"
  pullPolicy: IfNotPresent  # משתמש בתמונה שטענו ל-k3d

service:
  type: NodePort
  port: 5000



# אומר ל-Kubernetes להריץ את האפליקציה ב-Worker 2 בלבד
nodeSelector:
  workload: app

  