# helm/skywatch/values.yaml

replicaCount: 1

image:
  repository: skywatch-frontend
  tag: "c70ebbc21abf1628d687dc826865d96c97d02162"
  pullPolicy: IfNotPresent  # משתמש בתמונה שטענו ל-k3d

service:
  type: NodePort
  port: 5000



# אומר ל-Kubernetes להריץ את האפליקציה ב-Worker 2 בלבד
nodeSelector:
  workload: app

  