# helm/skywatch/values.yaml

replicaCount: 1

image:
  repository: skywatch-frontend
  tag: v1.0.0
  pullPolicy: Never  # משתמש בתמונה שטענו ל-k3d

service:
  type: NodePort
  port: 5000
  nodePort: 30000

# אומר ל-Kubernetes להריץ את האפליקציה ב-Worker 2 בלבד
nodeSelector:
  workload: app